logging:
  level:
    org:
      springframework:
        cloud:
          netflix:
            zuul: trace
server:
  port: 9000
spring:
  application:
    name: api-zuul
  sleuth:
    enabled: true
    sampler:
      rate: 1
zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    customer-service:
      path: /customer/**
      service-id: customer-service
    pet-service:
      path: /pet/**
      service-id: pet-service
